version: '3.8'
services:

  alexbackend:
    image: cfrancisco10/alexbackend
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m
    ports:
      - 3000:3000

  alexfrontend:
    image: cfrancisco10/alexfrontend
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '5'
    ports:
      - 8800:8800
